### ISSUE TITLE
ghost button pixel alignment isssue

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#126]
carbon white theme Ghost button with icon appears to have a slight pixel alignment issue with the default icon (standard resolution screen).

![image](https://user-images.githubusercontent.com/51379566/59705903-544a7600-91cd-11e9-8cf7-52d86e41b3d3.png)

**Comment by aagonzales** [comment]
Its hard to see in your small image but I believe nothing is wrong here. The pixel alignment is intentional due to the 1px style artwork of the new icon set. The 1px `+` will never sit perfectly on the pixel grid while also be centered.

![image](https://user-images.githubusercontent.com/11670886/60624398-ca90d000-9daa-11e9-90d6-9d78b70b06e7.png)

**Comment by chrisconnors-ibm** [comment]
It looks like this symbol probably isn’t using the current svg from carbon-elements (something that will be addressed soon) but it should matter in any case bc the actual code components should be, and no one should be generating assets from the design kit.
