### ISSUE TITLE
[design kits] Color profiles and color picker

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#212]
**Color profiles:**
Should we add a color profile to our kit files? We currently used the default for sketch which is called 'Unmanaged'. Mitch brought up that the colors may looks different across monitors unless they did have a profile.

**Color picker:**
Also is it possible to have the colors be added in the color picker so they can be easily picked in making things that are not in symbols?

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
Color profiles:
I changed the kits to have the RGB color profile, seems like this is the best profile to have especially since our users could be working on different kinds of computers with different kinds of display settings. This way the color of our kits should appear consistently across the board intsead of using "Unmanaged"

Ref: https://www.sketch.com/support/troubleshooting/color-management/

**Comment by laurenmrice** [comment]
Color picker: It may be possible to have colors from our libraries to be set as local, so they automatically show up in peoples files in their color palettes.

**Comment by mariuszmickiewicz** [comment]
> Color picker: It may be possible to have colors from our libraries to be set as local, so they automatically show up in peoples files in their color palettes.

Yes, this is possible. A color has to be added inside the library to the "document" palette and then it will be visible in the files using that library in dropdown below the color picker. 

The cons are:
* designers will use it instead of layer styles and this will prevent their designs to be be updates when the palette adjusts and they will loose the ability to easily switch themes
* yet another place to maintain the palette 

It wouldn't be a bad idea to add this functionality to IBM DL V2 library, where colors are not UI tokens. If used by designers however it makes FEDs' life harder, as they wouldn't be able to see the name of the color in inVision inspect.
 
![image](https://user-images.githubusercontent.com/12408951/82474466-657dc000-9acb-11ea-819b-179f25056dea.png)

**Comment by grahamharper** [comment]
I'd be in favour of adding the color tokens as presets to the library document. The current experience of using layer styles for color is limiting because layer styles set specific properties like fill or border (or several rolled into the same style). The current design kit only has layer styles for fills and not borders, which means you can't apply a color to a border only or say, a fill and a border. Adding the tokens are color presets would allow you apply a color token to any property, for example I could use $support-02 as a border color.

Here's how to do it: https://www.sketch.com/docs/libraries/#how-to-create-library-presets

> If used by designers however it makes FEDs' life harder, as they wouldn't be able to see the name of the color in inVision inspect.

Color preset names actually do show up in InVision inspect. I created a test where I made a local copy of a Carbon button symbol, created a local color preset for `#0f62fe` and called it `$interactive-01` then applied it to the symbol.

![Screenshot 2020-06-17 at 10 34 11](https://user-images.githubusercontent.com/2853295/84881807-47818c00-b086-11ea-96f7-8bc09ab93710.png)

**Comment by grahamharper** [comment]
One drawback I see for maintenance. It appears that you can't edit the underlying value of a color preset, you can only rename it. So a present doesn't behave like a variable where you create it and can change the underlying value, instead you're really just _naming_ a value.

![image](https://user-images.githubusercontent.com/2853295/84883003-f2467a00-b087-11ea-813b-c93a33350115.png)

Your only option is to change the name of the preset. If you try to modify the value in the field above it, it just deselects the preset and it remains unchanged.

**Comment by mariuszmickiewicz** [comment]
@grahamharper Hi, thanks for the insights. 
Can you let me know where you use $support-02 as a border color? Is it some custom component you've created?

**Comment by grahamharper** [comment]
Just a throw away example really.

I was doing a quick mockup and wanted the left border of a container highlighted green. Ended up using a rectangle instead of a line with a stroke.

**Comment by mariuszmickiewicz** [comment]
**Color picker**
This will be the solution (when it is released)
https://github.com/carbon-design-system/carbon-design-kit/issues/376

**Comment by mariuszmickiewicz** [comment]
Color variables are now live. Accessible via IBM Design Language (v2) library.
