### ISSUE TITLE
IBM Design Lanugage V1 Sketch file has several shared style typos/mistakes

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#227]
## Title line template: [Title]: Brief description
The IBM Carbon Design Language Sketch file has several mistakes in the shared styles. 
## Detailed description

Most are simply typos, but there are also missing styles. Considering that the carbon themes still use some of these styles, I figured it was worth mentioning. 

1. `color/blue/70 hover is missing. `
2. `color/gray/40 hover` is actually `color/gray/40 hove` (missing the r).
3. There are two `color/red/20` colors. One should be `red/20 hover`, but is named the same as red/20

```
color/red/20
color/red/20
```

4. color`/warm gray/30 2` is the name, but it should probably be `color/warm gray/30 hover`

> What version of the Carbon Design System Kit are you using?
Version downloaded from https://www.carbondesignsystem.com/get-started/design

## Steps to reproduce the issue

1. Download the sketch file and view shared style names (use automate to write style names to layer names or sketch style manager plugin). 

## Additional information

* Is there a excel spreadsheet or pdf with the actual v1 color names/numbers? I'd like to forget about the v1 palette all together, but without knowing which colors are still being used by the carbon themes I need to keep an inventory of it. Better yet, would be a list of v1 colors that are still being used in the Carbon themes until you guys update them with lighten/darken as you'd mentioned was the plan.

As an aside, I found a plugin called 'shared style finder' which shows you an inventory of all the styles and where they're from which is helpful to see what's going on in the sketch doc. There are a ton of IBM Language (v1) layer style references throughout the document still. I'm assuming most of those colors are either incorrect, or are simply the same colors as in the v2 doc and therefore didn't change. It would be pretty fast to go through and update those to point to the v2 doc, but the changes would be lost in an update. But as it stands currently, it would seem that any changes to colors would have to be made in both the v1 and v2 documents in order for the theme to adopt all the changes if I'm not mistaken.

Example:
https://snipboard.io/qhRKN8.jpg

## Add labels

type:bug

**Comment by josh-tt** [comment]
As an aside, I found a plugin called 'shared style finder' which shows you an inventory of all the styles and where they're from which is helpful to see what's going on in the sketch doc. There are a ton of IBM Language (v1) layer style references throughout the document still. I'm assuming most of those colors are either incorrect, or are simply the same colors as in the v2 doc and therefore didn't change. It would be pretty fast to go through and update those to point to the v2 doc, but the changes would be lost in an update. But as it stands currently, it would seem that any changes to colors would have to be made in both the v1 and v2 documents in order for the theme to adopt all the changes if I'm not mistaken. 

Example:
https://snipboard.io/qhRKN8.jpg

**Comment by laurenmrice** [comment]
We need to update the getting started section to have the link to the IDL v2 asset instead of v1 (I will make an issue for this if there isn't one already). 

We created the IDL v2 library from Carbons code base, so it will be updated with the newest colors, type, and eventually pictograms (Icons now have their separate libraries, you can find them on the Resources page and will also will be generated from our codebase). 

We will no longer be updating/supporting the v1 library. The colors we are currently using in code are in the IDL v2 library. When you can, I would start moving over to the IDL v2 library and Icons libraries to receive future updates.

We don't have a an excel spreadsheet or pdf of v1 colors. We do have this link to our elements that always has the latest color values and theming of our system. https://carbon-elements.netlify.com/ if that is helpful
