### ISSUE TITLE
ghost button icon wrong colour

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#284]
white theme / ghost button with icon.  the icon is coming out of the kit with the wrong colour.

I checked, it's correct in the gray 10 theme

top-white theme
bottom-gray 10 theme
![image](https://user-images.githubusercontent.com/51379566/74442917-550cd800-4e40-11ea-9b8e-454a448e0a87.png)

**Comment by laurenmrice** [comment]
This is a sketch bug. Did you update to the newest version recently, I just did and this also happened to me this morning when I tried to use the ghost button in the white theme. The button is correct in the master file. 

I have enabled overrides for the icon color so it can be changed back. I am going to open a bug issue about this with Sketch because its been happening a lot recently with other components.
