### ISSUE TITLE
Add size variations for inputs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#289]
Inputs are receiving `sm` and `xl` size variations that need to be added to the kit. 
Is there a way to adjust the height of the input field without creating a new symbol set? 

-----------------------------------------------------------------------------------------------------------------------------

Dropdown/Combobox/Multi-select: (in code) @laurenmrice DONE 🤩
- [x] White theme
- [x] Gray 10 theme
- [x]  Gray 90 theme
- [x] Gray 100 theme

-----------------------------------------------------------------------------------------------------------------------------

Date picker: (in code) @aagonzales DONE!
- [x] White theme
- [x] Gray 10 theme 
- [x]  Gray 90 theme 
- [x] Gray 100 theme 

_Note: Time picker doesn't have size variant in code so it was not included._

-----------------------------------------------------------------------------------------------------------------------------

Text input: (in code) @aagonzales DONE!
- [x] White theme 
- [x] Gray 10 theme 
- [x]  Gray 90 theme 
- [x] Gray 100 theme 

-----------------------------------------------------------------------------------------------------------------------------

Select: (in code) @aagonzales  DONE!
- [x] White theme 
- [x] Gray 10 theme 
- [x] Gray 90 theme 
- [x] Gray 100 theme 

-----------------------------------------------------------------------------------------------------------------------------

Number input: (in code) @laurenmrice  DONE!

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

_Note: also adding helper text and no label versions._

-----------------------------------------------------------------------------------------------------------------------------
File uploader: (in code) @laurenmrice 

- [x] White theme
- [x] Gray 10 theme 
- [x] Gray 90 theme
- [x] Gray 100 theme

**Comment by laurenmrice** [comment]
I sent sketch a support question if this is possible. I only have gotten it to work for inputs without labels.

**Comment by mariuszmickiewicz** [comment]
There is a way to adjust the height of a text field symbol without creating a new one, even with a label.  

![2020-05-20-input-size](https://user-images.githubusercontent.com/12408951/82469376-3283fe00-9ac4-11ea-9964-61b7ac93b29a.gif)

This will however put the responsibility to resize to the correct height on designers. Changing input itself from 40 to 32 or 48 is easy, but when label (or more elements like error, info — I would need to check if Sketch can handle that) is present, now some calculations are required and this will lead to guess work, mistakes in designs etc. 

Technically it is possible to have one symbol in Sketch for input field in all its states (hover, disabled, placeholder, focus), but I think the power of Carbon kit lies exactly in having all of the separate states with simple symbol switch, rather than tweaking sub-symbols and overrides. That's why I would suggest to create separate groups for other sizes. I can help with that.

**Comment by laurenmrice** [comment]
Did your approach work for the `error` state? That is what ended up blocking me from this in the end.

**Comment by mariuszmickiewicz** [comment]
If a label, helper text and error don't need to be multi-line (no smart layout involved) then _one symbol for all sizes_ approach seems to be working. It doesn't even needs that much of a cognitive load, just remember the sizes, add/remove 8px. 

Still, _predefined sizes_ approach for me sounds better, even if it requires a lot of maintenance, but I leave the decision to you.  

![image](https://user-images.githubusercontent.com/12408951/82472212-1e420000-9ac8-11ea-9058-1e1355352cdc.png)

**Comment by laurenmrice** [comment]
Lets go with this base naming structure for components that need a `size` selection.
<img width="676" alt="Screen Shot 2020-08-11 at 12 58 57 PM" src="https://user-images.githubusercontent.com/43969356/89933461-b1c13380-dbd4-11ea-8adb-bc03fee4bb36.png">

----------------------------------------------------------------------------------------------------------------------------

We can keep a top level section for `pieces` that don't need options for sizes. But for components that do have `pieces` that have different sizes, we can add a nested pieces section.

Ex:
<img width="422" alt="Screen Shot 2020-08-11 at 12 59 31 PM" src="https://user-images.githubusercontent.com/43969356/89933767-2c8a4e80-dbd5-11ea-933a-d51fc70236b4.png">

**Comment by laurenmrice** [comment]
Added! Will be in next kit update 🎉
