### ISSUE TITLE
[Sketch Library] Interactive tag > icon and text are not aligned within a pill

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/carbon-design-kit#314]
Interactive tag - icon and text are not aligned within a pill

Detailed description

![image](https://user-images.githubusercontent.com/24441071/79772970-ca909b00-82fe-11ea-9454-00df137a6543.png)

**Comment by laurenmrice** [comment]
Are you still finding this is not aligning? Which Theme are you using? I recreated this with the White and Gray 10 them so far, and it seems correct.
<img width="833" alt="Screen Shot 2020-04-21 at 2 46 33 PM" src="https://user-images.githubusercontent.com/43969356/79907241-e66b6e00-83de-11ea-8d39-6aa4fed1ff2f.png">


Would you mind also checking the `tag` component to see if those are misaligned (type riding high)?  For some people, they are getting this result and for others it looks fine and I am not sure what the problem is.

**Comment by assiroud** [comment]
I do find these a bit off :-( Not a biggie. Just because everything else is so perfect.
Using gray 10, Sketch 64. No issues with tags in the same theme. What do you think can be a reason? I'm puzzled.
![image](https://user-images.githubusercontent.com/24441071/79912371-eb84e900-83ef-11ea-82ab-32f556b91ffe.png)

**Comment by aagonzales** [comment]
Oh it was off in the multi-select custom tag. Lauren was probably checking the normal tag component not the one within dropdown.

**Comment by aagonzales** [comment]
Fixed! Available in the next kit update.

**Comment by assiroud** [comment]
Awesome! Thanks Anna :-)
