### ISSUE TITLE
Form component missing from carbon-design-kit 8.1.0

### ISSUE THREAD

**Issue by KimberlyGreene** [carbon-design-system/carbon-design-kit#32]
## Detailed description

I added version 8.1.0 of the Carbon Design Kit to Sketch. In the component listing, in Sketch, the Form component is missing.  The website (http://carbondesignsystem.com/components/form/usage) lists the component as design and develop ready but it's not available in the sketch design kit.

> What version of the Carbon Design System Kit are you using? 8.1.0

> Is this issue related to a specific component? form

> What did you expect to happen? What happened instead? What would you like to see changed?
Add the form component to the design kit.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency? yes. website says the component is design read but the kit doesn't include it.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM University Relations Awards Tool using Angular 5, Carbon, LoopBack, db2 on Cloud.

## Steps to reproduce the issue

1. download design kit 8.1.0 from git
2. add design kit library to Sketch
3. Choose Insert --> Carbon Design Kit --> Component
4. See Form component is not listed

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by tay-aitken** [comment]
Hi @KimberlyGreene 👋. An example of a form can be found on the components page in the Carbon Design Kit sketch file. We intentionally did not include a form symbol in the library because there is no set configuration for a form. Each configuration is based on individual use cases and customized to fit that need. Creating a form symbol in the library would have made it harder to customize since not all the sizing on form components are the same making the symbol swap out process very time consuming and manual.  We found that it was much easier for designers to pull the individual components they needed from the library and build their form that way. Hope that helps!

**Comment by tay-aitken** [comment]
Closed due to inactivity.
