### ISSUE TITLE
[multi-select dropdown] add selected background color

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#326]
Need to add `selected-ui`background to selected options.

![Screen Shot 2020-06-08 at 1 48 07 PM](https://user-images.githubusercontent.com/43969356/84063671-04892f80-a987-11ea-921a-025cec8b64bf.png)

**Comment by mariuszmickiewicz** [comment]
This is fixed in all themes. Will be live with next cloud upload (waiting for more updates to be ready).

**Issue**
Divider is currently at the top of each cell — this means that selected cell and the one directly below it create "stairs" pattern (see attached image). 

This can be fixed by moving the divider at the bottom of each cell. It will require turning off the border in the last item.  

![image](https://user-images.githubusercontent.com/12408951/84371455-fa12a400-abd9-11ea-98aa-7b7af4353941.png)

**Comment by laurenmrice** [comment]
Yeah for this we can just set the rule to the `transparent` layer style and if people change the states around they can change the rules back to ui-03.
