### ISSUE TITLE
sketch: is there a breadcrumb group symbol without trailing slash?

### ISSUE THREAD

**Issue by myan9** [carbon-design-system/carbon-design-kit#346]
Hi! I'm using CarbonDesignSystem.sketch to build the UI template of my project.  When I was trying to use the Breadcrumb groups symbols, I found all groups have a trailing slash after the last breadcrumb. But when I implemented the Breadcrumbs React Component, I can specify a `noTrailingSlash` React prop to disable that. So I'm wondering if there's an easy way for me to achieve that using Breadcrumb groups symbols. Thanks!

**Comment by laurenmrice** [comment]
You can achieve this in the kit by building the breadcrumb with `items` instead of using a `group`. The current state leaves out the trailing slash
<img width="1431" alt="Screen Shot 2020-07-27 at 9 33 47 AM" src="https://user-images.githubusercontent.com/43969356/88554563-4714d300-cfec-11ea-932f-7bea50ffe060.png">
