### ISSUE TITLE
[File uploader] pattern size in Sketch Kit

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/carbon-design-kit#408]
## Detailed description

File uploader size in the Sketch Kit is the same for large, medium and small patterns (and yes, I checked the size is set to original :-) 

Theme used - Gray 10

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/24441071/106172018-465a2680-6160-11eb-96a0-34328acc3158.png">

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/24441071/106172390-c7192280-6160-11eb-891b-5c52ce5cee59.png">

**Comment by laurenmrice** [comment]
The bucketing of `large, medium, small` has to do with the height size of the `primary button` and `uploaded file` for the `default file uploader`. This logic also applies to the `drag and drop file uploader`, but is not as obvious since the uploaded file state shows this size change and there isn't a button in this case.  The drag and drop container should stay the same, unless you need to change the size for your usecase.

It was bucketed this way to follow how we bucket other form components that have three different sizes. So you can make sure you are choosing components that have the same sizes if they are being placed on the same page or flow.

![Artboard](https://user-images.githubusercontent.com/43969356/107436458-2c6efb00-6af3-11eb-94f0-50e0a43aba62.png)
