### ISSUE TITLE
v11 [tooltip] update styles to accomodate new toggletip component

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-design-kit#483]
Update tooltip symbol

- remove interactive elements inside tooltip
- check caret sizing to make sure it's right

**Comment by laurenmrice** [comment]
### Standard tooltip
- [x] Made new group and item symbols.
- [x] Renamed "Interactive tooltip" group and item symbols to "Toggletip" and moved to the Toggletip component.

### Icon button tooltip
- [x] Item: Adjusted padding in tooltip around text to be 2px instead of 3px.
- [x] Group: Adjusted padding between icon and tooltip to be 4px instead of 8px.
- [ ] Question: Should we use the real button component in this instance or keep it the same for now? It will break peoples symbols if we change it.

### Definition tooltip
- [x] Didn't change anything.

-----

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Updated! Will be available in the next Sketch kit update. 🎉
