### ISSUE TITLE
Tertiary button w/ icon - smart layout issues

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#493]
sketch kit white theme

icon in the button isn't flowing as expected.

https://user-images.githubusercontent.com/51379566/156252558-86ec313b-1c2e-43bb-bafb-ed40a095e640.mov

**Comment by marceltrautmann** [comment]
unsure how it relates but someone sent me a file that had this in it??

![image](https://user-images.githubusercontent.com/51379566/156253412-b7b49f1e-586e-44fc-b07c-cacfcaeb5085.png)

**Comment by jayleighblak** [comment]
I'm seeing the same issue with the Sketch kit Gray 10 theme. I think the fix is to enable 'Adjust content on resize' on the **button / 03 tertiary / default / 02 text and icon / 01 enabled**  symbol

<img width="667" alt="Screen Shot 2022-03-04 at 13 44 12" src="https://user-images.githubusercontent.com/23215629/156823961-1de76153-9918-4c2c-9e9e-9f6d25b61798.png">

Additionally, during my investigation of this issue, I noticed a minor issue with the button sizes. When I changed the button label to 'Meeting' across multiple styles, the button widths were slightly different. There is extra space between the **label** layer and the **spacer** layer in these two button style symbols: **button / 01 primary / default / 01 text / 01 enabled** and **button / 02 secondary / default / 01 text / 01 enabled**. The other button styles that are consistent in width (132px in the image below) have no space between those layers. 

<img width="1042" alt="Screen Shot 2022-03-04 at 13 53 51" src="https://user-images.githubusercontent.com/23215629/156826452-9f3615e0-ccef-4e74-abec-8b203ed62206.png">
