### ISSUE TITLE
[Figma] Carbon v11 library updates 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#562]
Here is the list of items that need to be updated for Gray 10, Gray 90, and Gray 100. These are updated in White theme, so use White theme for reference. 

- [x] **Data table** / Miscellaneous updates @juanencalada 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Tabs** /  Hidden items update to 12 - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Tabs** / Add selected property - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Left panel nav items** / Hide icon left and icon right by default - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **UI shell nav items** / Add selected property to top, left, and right - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Tooltip** / Interaction states @laurenmrice 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Accordion** / Update names - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Button** / Add transparent fill to focus state - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **Search** / Use stroke instead of effects - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **UI shell** / Header spacer bottom border to use stroke instead of effect - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **UI shell** / Header actions auto layout right aligned - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **UI shell** / Header add bottom border - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **UI shell** / Header ‘Site name’ bottom border to use stroke instead of effect - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100
- [x] **UI shell** / Header ‘Site name’ remove transparent bg - @thyhmdo 
    - [x] Gray 10
    - [x] Gray 90
    - [x] Gray 100

**Comment by juanencalada** [comment]
@aagonzales @laurenmrice @thyhmdo

Hi friends! Data table is done! Thanks for your patience! It’s been completely refactored and should bee much more lightweight than it was previously. I’ve marked it as green in [White](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11-BETA)-White-Theme---Carbon-Design-System?node-id=24%3A0) and [Gray 10](https://www.figma.com/file/0sd447WTcazDI6Dq9tjXOe/(v11-BETA)-Gray-10-Theme---Carbon-Design-System?node-id=24%3A0) and yellow in [Gray 90](https://www.figma.com/file/fH8rkv1VUTw5pvFDvO1kPO/(v11-BETA)-Gray-90-Theme---Carbon-Design-System?node-id=4487%3A181347) and [Gray 100](https://www.figma.com/file/XhRIHF6qGiJQaJ5eOSSBRm/(v11-BETA)-Gray-100-Theme---Carbon-Design-System?node-id=4487%3A181347) because of something I noticed in the `Data table batch actions bar item`.

There seems to be some color discrepancies. Please review and let me know what colors I should update if any. Thanks!

**Comment by laurenmrice** [comment]
@juanencalada The buttons here should be using the ghost button instead of primary button. Anna commented on this in slack but wanted to also comment it here. Thanks!

**Comment by laurenmrice** [comment]
Finished!
