### ISSUE TITLE
[Question]: What is the 'resizer' component used for?

### ISSUE THREAD

**Issue by kunderwoodatadaptive** [carbon-design-system/carbon-design-kit#701]
### Question for Carbon

In the Figma library, I see the 'Resizer' component used in two places:

1. In the 'utilities' category of components for all 4 themes.
2. As a base within column cells of Data tables. (See screenshot.)

<img width="1240" alt="Screen Shot 2023-06-13 at 1 06 28 PM" src="https://github.com/carbon-design-system/carbon/assets/120414992/2c47de43-cd6e-4d58-8365-da1827f41c71">

What's the usage/purpose, in both cases?

Thank you!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by laurenmrice** [comment]
Hi @kunderwoodatadaptive 👋 

The resizer is a utility component used to specify a fixed width for layers inside a component instance since Figma doesn't allow manually specifying a fixed width for layers inside nested instances.

The resizer can be used to resize columns in the Data table component via the following steps:

1. Select the Data table
2. Run the ‘Select layers by name’ command from the ‘Select layers’ plugin
3. Type in the name of the column cells you wish to select i.e. ‘Col 1’ or ‘Col 4’ and click the ‘Select Layers by Name’ button
4. Set the horizontal Auto layout to ‘Hug contents’ for the column cells selected in the previous step
5. Rerun the ‘Select layers by name’ command from the ‘Select layers’ plugin by using the cmd + option + p keyboard shortcut
6. Type in ‘Resizer’ and click the ‘Select Layers by Name’ button
7. Adjust the Resizer’s Auto layout space between value to the desired value. Tip: The default value of the Resizer is 160
