### ISSUE TITLE
[Tile] Add feature flag

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#783]
## Acceptance criteria
- We accidentally pushed a change in Figma to the tile component, which changed the stable part of the component instead of adding a feature flag for it, as we do in code. 
- [x] We are going to have a discussion with designers, devs, and Juan on 03/15 to figure out how we want to show feature flags in Figma. 

---

**Note**

- [x] Start once the AI branch is merged for Tile, so there are no merge conflicts.

---

**To do**
- [x] Revert the Tile single-select styling to our stable single-select version as the default component.
- [x] Create Feature flag boolean and combine the Accessible border and Single select icon changes in it. This will make breaking change transitions smoother.
  - Naming convention for feature flag boolean: "[`name of enhancement`](`feature flag`)".
  - Consider adding an icon before the name for easier scanning of feature flags present in the properties panel. (For example like :golf: or any other icon that would make sense.)
- [x] Add a feature flag section in the "Description" for the Tile component. 
- [x] Review
     - [x] Thy
     - [x] Juan

**Comment by thyhmdo** [comment]
@Kritvi-bhatia17 Hi, just want to make sure that you check in with Juan about the radius corner variables once they're implemented. This may change the structural proposal you had. 

- Normal default tiles: Stable tiles (no border, no border radius) / Feature flag tiles (border, no border radius) 
- AI tiles: Default tiles (border, no border radius) / Optional AI tiles (border, 8px border radius)

**Comment by juanencalada** [comment]
1. I removed the Accessible property
2. I fixed an issue with the AI revert button
<img width="465" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/61653d17-e2aa-425e-8d73-2aaba0dc7373">
3. I fixed an issue with the AI slug placement when the feature flag is off for radio tile
<img width="594" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/fc1780c4-6978-4ce2-ad73-71ad1d23c19f">

**Comment by juanencalada** [comment]
1. Some of the AI layers were using the field instead of background. I changed them to background
2. For certain tiles, we need to resolve this extra space
<img width="654" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/30a53dff-690b-4219-a562-39e29bd3a270">
3. I think we should look at reconsolidating these layers
<img width="239" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/cf7bc118-3eee-4a3b-b9ba-eb63bf9ea023">
4. With those sections separate, it's creating issues like this:
<img width="872" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/2e69208d-2473-4119-b312-b5239ff03ccc">
5. For future consideration, do we need disabled expandable tiles?
<img width="522" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/192c52d6-2b69-4780-aa11-a2bd7f76d340">
6. I think this should be 32px if we want to base it off of what Dotcom is doing
![image](https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/77defcd1-8951-4f69-993f-a071e9143b51)

**Comment by juanencalada** [comment]
1. We can also look at including min-height of aspect ratio as optional in the future
2. Should the AI shadow have a Boolean property to make it optional in case the tile should not be floating? I went ahead and added it but we can of course remove if needed

**Comment by juanencalada** [comment]
@laurenmrice @Kritvi-bhatia17 @thyhmdo

**Comment by thyhmdo** [comment]
@juanencalada Hey Juan, thanks for the feedback!

1. Only the hover states get the AI background. Other states should have AI field layers. Anna has to update these layers in the future. 
2. The extra space on the right is fine. We'll reserve it when the text runs too long.
3. I think it should be fine. Usually, it's a place for the title + body text. I don't think people would hide the title text. 
4. Same thought as #3
5. Yes. We should add disabled states. 
6. I just learned that in the code, we have the absolute position for the icon and there's no way figuring out the space between the text and the icon... And our guidance states that there's 16px...But yeah maybe we can be consistent with dot com for now since we can't tell what's the spacing there in the Core Carbon code

**Comment by Kritvi-bhatia17** [comment]
> 7\. With those sections separate, it's creating issues like this:

Thanks a lot @juanencalada !!
Hi @laurenmrice, should I be fixing the 5th and 6th point in the [Tile's current branch](https://www.figma.com/file/YRImX5KCwYmC3lFjCuvG2o/Tiles-(Selectable-Components)-(Kritvi)?type=design&node-id=20125-279429&mode=design&t=t97wouweYPYlTXDp-4) only?
