### ISSUE TITLE
[Tabs]: incorrect disabled text token

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#791]
## Acceptance criteria

Line tabs are using the wrong color token for disabled text. The color token should be `$text-disabled`.

- [ ] Fix the line tabs disabled state to use `$text-disabled`.

**Comment by thyhmdo** [comment]
- Checked the code 
- Checked with Anna and Tracey
- It looks like we're using `button-disabled` as the background so we paired it with `text-on-color-disabled`. However, `text-disabled `would work too since it is an opacity value now
- This logic works the same for icons as well. `icon-on-color-disabled` or `icon-disabled` should work. 
- It's up to Tracey to update the Tab doc and we will decide to update this token if anything is changed.

**Comment by kingtraceyj** [comment]
code is using `text-on-color-disabled` so i'm inclined to keep it especially with the color background. i think it follows the token logic.

**Comment by thyhmdo** [comment]
Updated the Line tab with `text-disabled `
