### ISSUE TITLE
Define theme strategy for symbols

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#80]
### The problem 

We need a way to show that there are 3 more themes for our symbols coming down the road. Currently, symbols dropdown do not reflect any theme options: 

![image](https://user-images.githubusercontent.com/15144993/54371486-75884d00-4647-11e9-90f2-bf0792616eb7.png)

However, type styles are organized this way: Theme folder contains a full set of type styles: 

![image](https://user-images.githubusercontent.com/15144993/54371012-a916a780-4646-11e9-9080-24dd27827896.png)

### The task

- We should decide if we want to do the same "Theme folder" solution as type styles for symbols, or a different strategy. 
- Worth researching if changing the path of a symbol would break the symbol for our users. If it doesn't break the symbols on users end, we have the flexibility to change that folder organization later if needed.

**Comment by mattrosno** [comment]
This is so we can make our best effort at preventing breaking changes when v11 comes around, file symbol "file path" depends on a theme name.

**Comment by shinytoyrobots** [comment]
Do we have any further progress on this issue?

**Comment by aagonzales** [comment]
Related issue: https://github.com/IBM/carbon-design-kit/issues/70

It's still in progress, with all the workshop and other meetings that have been happening I haven't been able to finish this work. We weren't prioritizing it since it wasn't a stop ship but we should be able to have it done by end of next week (if people stop scheduling full day workshops for us lol).

As per the strategy of it, it will be all 4 themes in one file with the theme being the first option the user makes in the library. 

![image](https://user-images.githubusercontent.com/11670886/55095299-edae3400-5085-11e9-86f1-10862899a293.png)

**Comment by mattrosno** [comment]
@aagonzales better option for things that are theme-agnostic?

Component > Theme > Modifiers(s)/State(s)

or

Component > Modifiers(s)/State(s) > Theme

<img width="1680" alt="Screen Shot 2019-03-27 at 12 23 17 PM" src="https://user-images.githubusercontent.com/1691245/55098119-3d432e80-508b-11e9-99b8-15482d60c39d.png">

Maybe theme is always the last option?

If the symbol is theme-agnostic, it doesn't have themes as last options? But to future-proof it, should we always have a theme in the symbol path somewhere so if in the future it changes per theme?

How is symbol naming affected?

**Comment by shinytoyrobots** [comment]
@aagonzales - if not stop ship then I'm moving into `v10-update` milestone (but obviously if we get it done earlier, great)

**Comment by aagonzales** [comment]
Each theme has its own separate library/file.
