### ISSUE TITLE
[Dropdown] Audit inconsistent state transitions for all variants

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#818]
## Acceptance criteria
- There are several buggy interaction state transitions across the Dropdown, Multiselect, and Combobox components in Figma that need to be resolved.
-  [ ] Conduct an audit and document any bugs when using the variants panel.

---

**Filterable Multiselect (default style)**
1. [FOCUS] In the enabled state:

   > Clicking on "Selected" transitions to "Selected+Focus" instead of solely "Selected".
   > Toggling off "Selected" redirects to the "Focus (Enabled)" state rather than returning to the "Enabled" state.
   > 
   > ![Screen Recording 2024-05-20 at 2 19 39 PM (1)](https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/4d55e7a4-32a4-47ac-9586-5148af297648)

---

**Dropdown (fluid style)**

2. [OPEN] In the enabled state:

   > Clicking on "Open" transitions to "Focused Selected", but closing it returns to "Focused (Collapsed)".
   > 
   > ![Screen Recording 2024-05-20 at 2 34 59 PM (1)](https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/4e001628-e409-48a7-a39a-5e52371b5c53)

---

**Dropdown (default style)**

3. When you open the Dropdown, and click the “Selected” toggle in the right panel, the top field indicate an option has been selected, but the option in the menu only gets a focus state and a text color change, and no selection background state or checkmark icon in it. 

   > ![May-20-2024 10-32-37](https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/b4d496d9-a26d-4513-85c9-7115d9c26f8b)

---

**Combobox (default style)**

4. When you open the Combobox, it directly puts you into an error state. This should not be an error state and is causing confusion to our users. 

   >  ![error combobox](https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/8eaaf84b-d17a-4c9d-85fd-de9b81c2c128)

---

**Comment by thyhmdo** [comment]
Github issues response:
1. When opening and closing the menu using Mouse and Keyboard, it should be the expected behavior. This also needs to be clear in the sense that users shouldn't change the state of the menu option when they're using the Placeholder variant (Figma). Use the Preselected variant (Figma) instead.

2. When opening and closing the menu using Mouse and Keyboard, it should be the expected behavior.

3. I think this version has been updated. I can't find the selected prop anymore

4. See this update in the Audit below


### Bug + Code alignment

First round of auditing. View in this [Figma branch](https://www.figma.com/design/ymh7w0zbA4U6j1n69V1bMK/Dropdown-audit-(Thy)?node-id=76323-908491&t=xRGcUE4Za1dWvA5W-4). 

<img width="1400" alt="Bug + Code alignment" src="https://github.com/user-attachments/assets/f4746d36-6afc-4ce6-bcf2-e67672e7d9fe">

**Comment by thyhmdo** [comment]
Nevermind... [This implementation](https://github.com/carbon-design-system/carbon/pull/16789) is in the process. So it's against some of our current behaviors. This will need an update. Let's wait until the implementation goes through before continue doing this audit.

**Comment by thyhmdo** [comment]
Follow up with [next steps in this Figma file](https://www.figma.com/design/CRHy2iRJ7J427rBpPoOaBV?node-id=3686-29599#913653700). After that, the [Dropdown branch](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/branch/ymh7w0zbA4U6j1n69V1bMK/(v11)-All-themes---Carbon-Design-System?m=auto&node-id=14032-290630&t=uwV93jteHvWp5mPz-1) is ready to be updated, focusing on the focus and invalid states.
