### ISSUE TITLE
Make clr file and color palette for kits

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#98]
We have gotten requests to add a clr color palette file for sketch or a palette for the plugin.

- May need a dev to help make the clr file.
- Does this mean we need four separate clr files for the four different themes?

**Comment by mariuszmickiewicz** [comment]
Just a sidenote:
With the recent updates to Sketch creating a palette for the Sketch Palettes plugin is not necessary. 
If a library has "Document Colors" set up then this palette will be visible in the color dropdown in any document 9see image below).

Current solution where library provides _Layer Styles_ has that benefit that if some color changes in the library it will be pushed and updated in users' projects. The moment people start using palette instead of _Layer Style_ the connection with the library is lost (palette will update, but not the layers which are using that specific color). 

![image](https://user-images.githubusercontent.com/12408951/57525101-16367880-732a-11e9-9912-9c7dcc3ea88b.png)

**Comment by shixiedesign** [comment]
CLR file is created: 
[Uploading IBM_Colors_RGB.zip…]()
Next up working on getting it available via carbon site: https://github.com/carbon-design-system/carbon-website/issues/1624
